# Generated by Django 6.0.2 on 2026-02-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("summary", "Task Summary"),
                            ("priority", "Priority Prediction"),
                            ("delay", "Delay Prediction"),
                            ("workload", "Workload Analysis"),
                            ("similarity", "Similarity Detection"),
                            ("reminder", "Smart Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("input_data", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.userprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI Analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "analysis_type"],
                        name="ai_engine_a_organiz_9d4d8f_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="ai_engine_a_entity__9d2957_idx",
                    ),
                ],
            },
        ),
    ]
