# Generated by Django 6.0.2 on 2026-02-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("outlet_tasks", "All Outlets Tasks Report"),
                            ("outlet_issues", "All Outlets Issues Report"),
                            (
                                "employee_tasks",
                                "Employee & Outlet wise Tasks with Status",
                            ),
                            (
                                "employee_issues",
                                "Employee & Outlet wise Issues with Status",
                            ),
                            ("backlog", "Backlog Report"),
                            ("monthly_points", "Month On Month Userwise Points"),
                            ("outlet_checklist", "Outlet-wise Checklist Points Report"),
                            ("employee_taskwise", "Employee wise - Task wise Report"),
                            ("task_submission", "Task Submission Report Outlet-wise"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_key", models.CharField(max_length=255, unique=True)),
                ("data", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["report_key"], name="reports_rep_report__982774_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="reports_rep_expires_9e7899_idx"
                    ),
                ],
            },
        ),
    ]
