# Generated by Django 6.0.2 on 2026-02-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("task_completed", "Task Completed"),
                            ("task_overdue", "Task Overdue"),
                            ("task_comment", "Task Comment"),
                            ("issue_created", "Issue Created"),
                            ("issue_resolved", "Issue Resolved"),
                            ("project_update", "Project Update"),
                            ("form_response", "Form Response"),
                            ("ai_suggestion", "AI Suggestion"),
                            ("reminder", "Reminder"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("normal", "Normal"),
                            ("low", "Low"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("entity_type", models.CharField(blank=True, max_length=50)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="notificatio_user_id_f77590_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_46ad24_idx"
                    ),
                ],
            },
        ),
    ]
